FROM docker.io/library/ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive

# Install/Setup Part
RUN apt-get update && \
    apt-get upgrade --yes --no-install-recommends && \
    apt-get install --yes --no-install-recommends \
        g++ ninja-build cmake git ca-certificates \
        libeigen3-dev libboost-all-dev libsuitesparse-dev libfmt-dev libyaml-cpp-dev \
        libtbb-dev libopencv-dev libglew-dev

ARG cmake_version=3.27.9
RUN apt-get install --yes --no-install-recommends wget ca-certificates && \
    cd /tmp && \
    wget https://github.com/Kitware/CMake/releases/download/v${cmake_version}/cmake-${cmake_version}-linux-x86_64.sh -O cmake.sh && \
    chmod +x cmake.sh && \
    ./cmake.sh --prefix=/usr/local/ --skip-license && \
    rm -rf /tmp/*

ARG llvm_version=20
RUN apt-get install --yes --no-install-recommends lsb-release wget software-properties-common gnupg ca-certificates && \
    cd /tmp && \
    wget https://apt.llvm.org/llvm.sh && \
    chmod +x llvm.sh && \
    ./llvm.sh ${llvm_version} all && \
    rm -rf /tmp/*
ENV CC=clang-${llvm_version}
ENV CXX=clang++-${llvm_version}

# Build Part
ARG build_threads=0

RUN cd /tmp && \
    git clone -b v0.6 https://github.com/stevenlovegrove/Pangolin.git && \
    cd Pangolin && \
    cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release . && \
    cmake --build build --parallel $(test ${build_threads} -eq 0 && nproc || (printf ${build_threads})) && \
    cmake --install build

# Add non-root user
RUN useradd -m -s /bin/bash user && \
    chown -R user:user /home/user && \
    ldconfig
